export const FAKE_TIMEOUT = 3000;

export const categories = {
	A: 'Electronics',
	A1: 'Smartphones & Accessories',
	A2: 'Computers & Tablets',
	A3: 'Cameras & Photography',
	A4: 'Audio & Sound Systems',
	A5: 'Wearable Technology',
	B: 'Fashion',
	B1: "Women's Clothing",
	B2: "Men's Clothing",
	B3: "Children's Clothing",
	B4: 'Shoes',
	B5: 'Accessories & Jewelry',
	C: 'Home & Garden',
	C1: 'Furniture',
	C2: 'Home Decor',
	C3: 'Kitchen & Dining',
	C4: 'Garden & Outdoor',
	C5: 'Home Improvement',
	D: 'Beauty & Personal Care',
	D1: 'Skincare',
	D2: 'Makeup',
	D3: 'Hair Care',
	D4: 'Fragrances',
	D5: 'Personal Care Appliances',
	E: 'Sports & Outdoors',
	E1: 'Exercise & Fitness',
	E2: 'Outdoor Recreation',
	E3: 'Team Sports',
	E4: 'Camping & Hiking',
	E5: 'Cycling',
	F: 'Toys & Games',
	F1: 'Action Figures & Dolls',
	F2: 'Board Games & Puzzles',
	F3: 'Educational Toys',
	F4: 'Video Games & Consoles',
	F5: 'Outdoor Play Equipment',
	G: 'Books, Movies, & Music',
	G1: 'Books',
	G2: 'Movies & TV Shows',
	G3: 'Musical Instruments',
	G4: 'Vinyl Records & CDs',
	G5: 'Sheet Music & Songbooks',
	H: 'Art & Collectibles',
	H1: 'Fine Art',
	H2: 'Collectibles',
	H3: 'Handcrafted Goods',
	H4: 'Vintage Finds',
	H5: 'Art Supplies',
	I: 'Health & Wellness',
	I1: 'Dietary Supplements',
	I2: 'Health Monitors & Equipment',
	I3: 'Wellness Products',
	I4: 'Vision Care',
	I5: 'Weight Management',
	J: 'Automotive',
	J1: 'Car Parts & Accessories',
	J2: 'Motorcycles & Scooters',
	J3: 'Automotive Tools & Equipment',
	J4: 'Car Electronics',
	J5: 'Tires & Wheels',
	K: 'Pet Supplies',
	K1: 'Pet Food & Treats',
	K2: 'Pet Health & Wellness',
	K3: 'Pet Toys',
	K4: 'Pet Grooming',
	K5: 'Pet Beds & Furniture',
	L: 'Groceries & Gourmet Food',
	L1: 'Fresh Food',
	L2: 'Packaged Food & Snacks',
	L3: 'Beverages',
	L4: 'Gourmet Gifts',
	L5: 'Dietary Foods',
	M: 'Office Supplies',
	M1: 'Office Electronics',
	M2: 'Office Furniture',
	M3: 'School Supplies',
	M4: 'Writing & Correction Supplies',
	M5: 'Office Organization',
	N: 'Hobbies & Crafts',
	N1: 'Sewing & Knitting',
	N2: 'Painting & Drawing',
	N3: 'Scrapbooking',
	N4: 'Model Building',
	N5: 'Craft Supplies'
};
